const arazzoSymbols = [
  'arazzo',
  'arazzoSpecification1',
  'arazzo-version',
  'criteria',
  'criterion',
  'failureAction',
  'failure-action-criteria',
  'info',
  'JSONSchema',
  'json-schema-enum',
  'json-schema-properties',
  'json-schema-required',
  'json-schema-type',
  'parameter',
  'parameters',
  'requestBody',
  'result',
  'sourceDescription',
  'source-descriptions',
  'source-description-url',
  'spec-version',
  'step',
  'step-on-failure',
  'step-outputs',
  'step-parameters',
  'step-success-criteria',
  'version',
  'workflow',
  'workflow-failure-actions',
  'workflow-outputs',
  'workflows',
  'workflow-steps',
  'parameter',
  'reference',
  'schema',
  'operationId',
];

const symbols = [...arazzoSymbols];

export default symbols;
